import { useEffect, useRef, useState } from "react";

const go = (path: string) => { window.location.hash = path; window.scrollTo({ top: 0, behavior: "smooth" }); };

function AccessCard() {
  const [state, setState] = useState<"INVITED"|"CONFIRMED"|"ADMITTED">("INVITED");
  useEffect(() => { const t = window.setInterval(() => setState(s => s === "INVITED" ? "CONFIRMED" : s === "CONFIRMED" ? "ADMITTED" : "INVITED"), 2400); return () => clearInterval(t); }, []);
  return <div className="gold-card-wrap"><div className="gold-card"><div className="gold-card-top"><span>ENTRIA / PRIVATE ACCESS</span><span>01 — 03</span></div><div className="gold-card-event">MIDNIGHT<br/><em>LAGOS</em></div><div className="gold-card-meta"><div><small>GUEST PASS</small><strong>VIP · 00248</strong></div><div><small>STATUS</small><strong className={state === "ADMITTED" ? "ok-text" : "gold-text"}>{state}</strong></div></div><div className="gold-qr"><div className="qr-core"><span>◆</span></div></div><div className="gold-card-bottom"><span>ONE PASS · ONE ENTRY</span><span>08.11.26</span></div></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="access-float access-float-a"><span className="live-dot"/> LIVE GATE</div><div className="access-float access-float-b">{state === "ADMITTED" ? "ACCESS GRANTED" : "CRYPTOGRAPHIC PASS"}</div></div>;
}

export default function EntriaPublic() {
  const root = useRef<HTMLDivElement>(null); const [scroll, setScroll] = useState(0);
  useEffect(() => { const on = () => setScroll(window.scrollY); window.addEventListener("scroll", on, { passive: true }); return () => window.removeEventListener("scroll", on); }, []);
  useEffect(() => { const el=root.current; if(!el) return; const move=(e:MouseEvent)=>{ el.style.setProperty("--mx", `${e.clientX}px`); el.style.setProperty("--my", `${e.clientY}px`); }; window.addEventListener("mousemove",move); return()=>window.removeEventListener("mousemove",move); }, []);
  return <div ref={root} className="entria-public" style={{"--scroll": scroll} as React.CSSProperties}>
    <section className="ep-hero"><div className="ep-noise"/><div className="ep-grid"/><div className="ep-glow ep-glow-1"/><div className="ep-glow ep-glow-2"/>
      <nav className="ep-nav"><button className="ep-logo" onClick={()=>go("/")}><span>e</span> ENTRIA</button><div className="ep-navlinks"><a href="#experience">Experience</a><a href="#access">Access</a><a href="#control">Control</a></div><button className="ep-staff" onClick={()=>go("/staff/login")}>Staff portal <span>↗</span></button></nav>
      <div className="ep-hero-inner"><div className="ep-copy"><div className="eyebrow"><i/> NIGERIA · PRIVATE EVENTS · CONTROL</div><h1>THE INVITE<br/><span>IS THE ACCESS.</span></h1><p>Entria gives premium events one source of truth — who was invited, who confirmed, who has a pass, and who is actually inside.</p><div className="ep-actions"><button className="ep-primary" onClick={()=>go("/page/midnight-lagos")}>Experience an event <b>→</b></button><a href="#access" className="ep-secondary">See how it works ↓</a></div><div className="ep-proof"><span><strong>01</strong> invitation</span><span><strong>02</strong> confirmation</span><span><strong>03</strong> access</span></div></div><div className="ep-stage"><AccessCard/></div></div>
      <div className="ep-scroll">SCROLL TO ENTER <span>↓</span></div>
    </section>

    <section id="experience" className="ep-section ep-dark"><div className="section-kicker">01 / THE EXPERIENCE</div><div className="ep-split"><div><h2>Not a ticket.<br/><span>A controlled invitation.</span></h2></div><div><p className="lead">For celebrity launches, private dinners, concerts, festivals and high-value experiences, the guest list is part of the event itself.</p><p>Entria turns the invitation into a secure digital journey. Guests receive a discreet link, confirm their attendance and receive a personalized access pass. Staff see only what they need at the gate.</p></div></div><div className="ep-flow"><div className="flow-line"/><article><span>01</span><h3>INVITE</h3><p>Send a branded invitation by link, email or WhatsApp.</p></article><article><span>02</span><h3>RSVP</h3><p>Capture exactly who is coming — and the permitted headcount.</p></article><article><span>03</span><h3>PASS</h3><p>Issue a unique QR credential tied to the guest record.</p></article><article><span>04</span><h3>GATE</h3><p>Verify once. Admit once. Log everything.</p></article></div></section>

    <section id="access" className="ep-section ep-gold"><div className="ep-center"><div className="section-kicker">02 / ACCESS CONTROL</div><h2>SELL 1,000.<br/><em>LET 1,000 IN.</em></h2><p>Capacity is not a number on a report. It is a rule enforced at the door.</p></div><div className="control-visual"><div className="control-panel"><div className="cp-top"><span>LIVE EVENT / MIDNIGHT LAGOS</span><span className="cp-live">● LIVE</span></div><div className="cp-number">1,248 <small>/ 1,500</small></div><div className="cp-bar"><i/></div><div className="cp-grid"><div><small>CONFIRMED</small><b>1,337</b></div><div><small>ADMITTED</small><b>1,248</b></div><div><small>REMAINING</small><b>252</b></div><div><small>DUPLICATES BLOCKED</small><b>17</b></div></div><div className="cp-gate"><span className="gate-ring">✓</span><div><small>LAST SCAN</small><strong>ACCESS GRANTED</strong><em>VIP · 00248 · 18:43:12</em></div></div></div></div></section>

    <section id="control" className="ep-section ep-dark"><div className="section-kicker">03 / COMMAND</div><div className="ep-split"><div><h2>One event.<br/><span>Total control.</span></h2></div><div><p className="lead">The private staff workspace gives organizers a live view of the event without exposing operational controls to guests.</p></div></div><div className="ep-features"><div><b>Guest access</b><span>Invitation, RSVP, pass issuance</span></div><div><b>Premium ticketing</b><span>Paid, free, VIP and capacity tiers</span></div><div><b>Gate intelligence</b><span>One-time QR verification and logs</span></div><div><b>Event finance</b><span>Revenue, expenses and cost per guest</span></div></div><div className="ep-cta"><div><span>READY WHEN THE GUESTS ARE.</span><h2>Build the event.<br/><em>Control the room.</em></h2></div><button className="ep-primary" onClick={()=>go("/staff/login")}>Enter staff portal →</button></div></section>
    <footer className="ep-footer"><span>ENTRIA / EVENT EXPERIENCES</span><span>BUILT FOR NIGERIA · BUILT FOR CONTROL</span></footer>
  </div>;
}
