import { useEffect, useState } from "react";

const go=(p:string)=>{window.location.hash=p;window.scrollTo({top:0,behavior:"smooth"})};
const events=[
 {name:"Lagos After Dark",date:"12 SEP 2026",time:"8:00 PM — 2:00 AM",venue:"Eko Convention Centre · Lagos",price:"₦50,000",type:"LIMITED TICKETS",img:"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1800&q=85"},
 {name:"The Gold Room",date:"26 SEP 2026",time:"7:30 PM — LATE",venue:"Victoria Island · Lagos",price:"₦75,000",type:"INVITATION + RSVP",img:"https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1800&q=85"},
 {name:"Lagos Fashion Night",date:"10 OCT 2026",time:"6:00 PM — 11:00 PM",venue:"Landmark Centre · Lagos",price:"₦35,000",type:"TICKETS AVAILABLE",img:"https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1800&q=85"}
];
function Hero(){const [i,setI]=useState(0);const e=events[i];useEffect(()=>{const t=setInterval(()=>setI(x=>(x+1)%events.length),6500);return()=>clearInterval(t)},[]);return <section className="event-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(3,5,4,.92) 0%,rgba(3,5,4,.62) 48%,rgba(3,5,4,.2)),url(${e.img})`}}><nav className="event-nav"><button className="event-brand" onClick={()=>go("/")}><b>e</b><span>ENTRIA</span></button><div><a href="#events">Events</a><a href="#experience">Experience</a><a href="#about">About</a></div><button className="staff-link" onClick={()=>go("/staff/login")}>Staff portal ↗</button></nav><div className="hero-event"><div className="hero-tag">{e.type} · NIGERIA</div><h1>{e.name}</h1><p className="hero-date">{e.date} <i/> {e.time}</p><p className="hero-venue">📍 {e.venue}</p><div className="hero-price">From <strong>{e.price}</strong></div><div className="hero-buttons"><button onClick={()=>go("/page/lagos-after-dark")} className="gold-btn">View event <b>→</b></button><a href="#events" className="ghost-btn">Explore all events ↓</a></div></div><div className="hero-films">{events.map((x,n)=><button key={x.name} onClick={()=>setI(n)} className={n===i?"selected":""}><span>0{n+1}</span><strong>{x.name}</strong><small>{x.date}</small></button>)}</div></section>}
export default function EntriaPublic(){return <div className="entria-events"><Hero/><section id="events" className="events-section"><div className="event-section-head"><div><span className="gold-kicker">WHAT'S HAPPENING</span><h2>Experience<br/><em>Lagos differently.</em></h2></div><p>Discover curated events, premium celebrations and unforgettable nights. Every event is presented with the detail it deserves — date, place, access and price, all in one view.</p></div><div className="event-grid">{events.map((e,i)=><article className="event-tile" key={e.name} onClick={()=>go(`/page/event-${i+1}`)}><div className="tile-media"><img src={e.img} alt=""/><span>{e.type}</span><button aria-label="View event">↗</button></div><div className="tile-body"><div><span>{e.date}</span><h3>{e.name}</h3><p>📍 {e.venue}</p></div><div className="tile-price"><small>FROM</small><b>{e.price}</b></div></div></article>)}</div></section><section id="experience" className="access-section"><div className="access-copy"><span className="gold-kicker">THE ENTRIA EXPERIENCE</span><h2>From invitation<br/><em>to entrance.</em></h2><p>Whether you're buying a ticket or receiving a private invitation, Entria keeps the journey simple. Guests get a beautiful digital pass. Organizers get absolute control over the room.</p></div><div className="journey"><div><b>01</b><strong>DISCOVER</strong><span>Find the event, date, venue and price.</span></div><div><b>02</b><strong>RSVP / BUY</strong><span>Confirm your place and permitted headcount.</span></div><div><b>03</b><strong>YOUR PASS</strong><span>Receive your personal digital QR pass.</span></div><div><b>04</b><strong>ENTER</strong><span>One secure scan. One controlled entry.</span></div></div></section><section id="about" className="about-section"><span className="gold-kicker">BUILT FOR THE PEOPLE WHO MAKE THE NIGHT</span><h2>Beautiful for guests.<br/><em>Powerful for organisers.</em></h2><div className="about-cols"><p>Entria is an event access and ticketing platform built around the reality of premium events in Nigeria — where guest lists, capacity, privacy, last-minute invitations and a flawless entrance matter.</p><div><span>Private celebrations</span><span>Concerts & festivals</span><span>Conferences & masterclasses</span><span>Weddings & galas</span></div></div><button onClick={()=>go("/staff/login")} className="gold-btn">Organiser access →</button></section><footer><span>ENTRIA</span><span>LAGOS · NIGERIA</span><span>EVENTS / ACCESS / EXPERIENCE</span></footer></div>}
