import { useMemo, useState } from "react";
import { useApp } from "../lib/store";
import { addExpense, addGuest, addTable, checkInGuest, deleteExpense, getOps, seedFromAttendees, updateGuest, updateOps, type AccessMode, type RSVPStatus } from "../lib/operations";
import { Badge, Button, Card, Field, Input, Modal, Select, Textarea, useToast } from "../components/ui";

const modeCopy: Record<AccessMode, { title: string; desc: string }> = {
  guest: { title: "Guest Access", desc: "Invite-only, RSVP, plus-ones and controlled QR access." },
  ticketing: { title: "Premium Ticketing", desc: "Paid tickets, checkout, capacity and QR ticket access." },
  signature: { title: "Signature Event", desc: "Guest management plus seating, staff lanes and premium event operations." },
};

const statusTone: Record<RSVPStatus, "neutral" | "ok" | "warn" | "bad" | "teal"> = {
  pending: "neutral", invited: "warn", confirmed: "ok", declined: "bad", waitlist: "teal",
};

export default function EventOperations({ id, navigate }: { id?: string; navigate?: (to: string) => void }) {
  const { db, user } = useApp();
  const toast = useToast();
  const event = db.events.find(e => e.id === id) ?? db.events.find(e => e.status === "live") ?? db.events[0];
  const [ops, setOps] = useState(() => event ? getOps(event.id, event.tickets.reduce((s,t)=>s+t.capacity,0)) : getOps("unknown"));
  const [tab, setTab] = useState<"overview" | "guests" | "expenses" | "seating" | "access">("overview");
  const [guestOpen, setGuestOpen] = useState(false);
  const [expenseOpen, setExpenseOpen] = useState(false);
  const [tableOpen, setTableOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [guest, setGuest] = useState({ name:"", email:"", phone:"", allowedGuests:1, confirmedGuests:0, rsvp:"invited" as RSVPStatus, table:"", notes:"" });
  const [expense, setExpense] = useState({ category:"Venue", description:"", amount:"", paid:true });
  const [table, setTable] = useState({ name:"Table 4", capacity:"10" });

  if (!event) return <div className="p-8">No events available.</div>;
  const refresh = () => setOps(getOps(event.id, event.tickets.reduce((s,t)=>s+t.capacity,0)));
  const attendees = db.attendees.filter(a => a.eventId === event.id);
  const currentOps = useMemo(() => {
    const base = getOps(event.id, event.tickets.reduce((s,t)=>s+t.capacity,0));
    if (!base.guests.length && attendees.length) return seedFromAttendees(event.id, attendees.map(a => ({ name:a.name, email:a.email, code:a.code })));
    return base;
  }, [event.id, attendees.length]);
  const active = ops.guests.length ? ops : currentOps;
  const confirmed = active.guests.reduce((s,g)=>s + (g.rsvp === "confirmed" ? g.confirmedGuests : 0), 0);
  const invited = active.guests.length;
  const admitted = active.guests.reduce((s,g)=>s+g.checkedIn,0);
  const totalExpenses = active.expenses.reduce((s,e)=>s+e.amount,0);
  const revenue = db.orders.filter(o=>o.eventId===event.id && o.status!=="refunded").reduce((s,o)=>s+o.total,0);
  const balance = revenue-totalExpenses;
  const filtered = active.guests.filter(g => [g.name,g.email,g.phone||"",g.inviteCode].some(x=>x.toLowerCase().includes(search.toLowerCase())));
  const setMode = (mode: AccessMode) => { setOps(updateOps(event.id,{accessMode:mode})); toast({kind:"ok",title:"Event model updated",desc:modeCopy[mode].title}); };
  const addGuestNow = () => {
    if (!guest.name.trim() || !guest.email.trim()) return toast({kind:"bad",title:"Guest details required",desc:"Name and email are required."});
    addGuest(event.id,{...guest,allowedGuests:Number(guest.allowedGuests)||1,confirmedGuests:Number(guest.confirmedGuests)||0});
    setGuestOpen(false); setGuest({name:"",email:"",phone:"",allowedGuests:1,confirmedGuests:0,rsvp:"invited",table:"",notes:""}); refresh();
  };
  const addExpenseNow = () => {
    const amount=Number(expense.amount); if(!expense.description.trim() || !amount) return toast({kind:"bad",title:"Expense details required"});
    addExpense(event.id,{...expense,amount}); setExpenseOpen(false); setExpense({category:"Venue",description:"",amount:"",paid:true}); refresh();
  };
  const addTableNow = () => { addTable(event.id,table.name,Number(table.capacity)||10); setTableOpen(false); refresh(); };

  return <div className="mx-auto max-w-[1450px] px-5 py-7 lg:px-8">
    <div className="mb-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
      <div><div className="code-pill text-[10px] uppercase tracking-[.22em] text-faint">Event command center</div><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="font-display text-3xl font-black tracking-tight">{event.name}</h1><Badge tone={event.status === "live" ? "ok" : "neutral"}>{event.status}</Badge></div><p className="mt-2 text-sm text-mut">{event.venue} · {event.city} · {new Date(event.start).toLocaleString()}</p></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>navigate?.(`/events/${event.id}`)}>Edit event</Button><Button variant="dark" onClick={()=>setTab("access")}>Open gate</Button></div>
    </div>

    <Card className="mb-5 overflow-hidden bg-night text-white">
      <div className="flex flex-col gap-5 p-5 lg:flex-row lg:items-center lg:justify-between">
        <div><div className="code-pill text-[9px] uppercase tracking-[.2em] text-white/35">How this event works</div><div className="mt-1 font-display text-xl font-black">Choose the access model before guests arrive.</div><p className="mt-1 max-w-2xl text-xs leading-5 text-white/45">The access quantity is enforced independently from the buyer. A person cannot arrive with more guests than the invitation or pass permits.</p></div>
        <div className="grid grid-cols-3 gap-2">{(Object.keys(modeCopy) as AccessMode[]).map(m=><button key={m} onClick={()=>setMode(m)} className={`rounded-xl border px-3 py-3 text-left transition ${active.accessMode===m?"border-amber-200/40 bg-amber-100/10":"border-white/10 bg-white/[.03] hover:bg-white/[.06]"}`}><div className="text-[10px] font-black uppercase tracking-[.12em]">{modeCopy[m].title}</div><div className="mt-1 hidden text-[9px] leading-4 text-white/35 sm:block">{modeCopy[m].desc}</div></button>)}</div>
      </div>
    </Card>

    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      {[['Invited',invited,'guest'],['Confirmed',confirmed,'guest'],['Admitted',admitted,'check'],['Capacity',active.guestLimit || active.capacity,'cap'],['Net balance',`${db.settings.currency} ${balance.toLocaleString(undefined,{maximumFractionDigits:0})}`,'money']].map(([label,value,key])=><Card key={key} className="p-4"><div className="code-pill text-[9px] uppercase tracking-[.18em] text-faint">{label}</div><div className="mt-2 font-display text-2xl font-black">{value}</div>{key==='check'&&<div className="mt-2 text-[10px] text-mut">{confirmed ? Math.round(admitted/confirmed*100) : 0}% of confirmed guests</div>}{key==='money'&&<div className="mt-2 text-[10px] text-mut">Revenue {db.settings.currency} {revenue.toLocaleString(undefined,{maximumFractionDigits:0})} · expenses {db.settings.currency} {totalExpenses.toLocaleString(undefined,{maximumFractionDigits:0})}</div>}</Card>)}
    </div>

    <div className="mb-5 flex flex-wrap gap-1 rounded-xl border border-line bg-paper p-1">{(['overview','guests','expenses','seating','access'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-lg px-4 py-2 text-[12px] font-semibold capitalize ${tab===t?'bg-night text-white':'text-mut hover:bg-ink/[.04]'}`}>{t}</button>)}</div>

    {tab==='overview'&&<div className="grid gap-4 lg:grid-cols-[1.4fr_.8fr]">
      <Card className="p-5"><div className="flex items-center justify-between"><div><div className="font-display text-lg font-bold">Arrival picture</div><p className="text-xs text-mut">Live operational view for the team.</p></div><Badge tone="teal">{active.accessMode==='guest'?'RSVP event':active.accessMode==='signature'?'Signature':'Ticketed event'}</Badge></div><div className="mt-6 grid gap-3 sm:grid-cols-4">{[['Pending',active.guests.filter(g=>g.rsvp==='pending').length],['Invited',active.guests.filter(g=>g.rsvp==='invited').length],['Confirmed',active.guests.filter(g=>g.rsvp==='confirmed').length],['Declined',active.guests.filter(g=>g.rsvp==='declined').length]].map(([l,v])=><div key={l} className="rounded-xl border border-line bg-white p-4"><div className="text-[10px] uppercase tracking-wider text-faint">{l}</div><div className="mt-1 text-2xl font-black">{v}</div></div>)}</div><div className="mt-6 rounded-xl border border-line bg-white p-4"><div className="flex justify-between text-[11px] font-semibold"><span>Confirmed guest capacity</span><span>{confirmed} / {active.guestLimit || active.capacity}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-ink/[.08]"><div className="h-full rounded-full bg-teal" style={{width:`${Math.min(100,((confirmed)/(active.guestLimit||active.capacity||1))*100)}%`}}/></div></div></Card>
      <Card className="p-5"><div className="font-display text-lg font-bold">Operational actions</div><div className="mt-4 space-y-2"><Button className="w-full" onClick={()=>{setTab('guests');setGuestOpen(true)}}>+ Add guest</Button><Button variant="outline" className="w-full" onClick={()=>setTab('access')}>Scan / admit guest</Button><Button variant="outline" className="w-full" onClick={()=>{setTab('expenses');setExpenseOpen(true)}}>+ Log expense</Button><Button variant="outline" className="w-full" onClick={()=>setTab('seating')}>Open seating</Button></div></Card>
    </div>}

    {tab==='guests'&&<Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-line p-5 lg:flex-row lg:items-center"><div className="flex-1"><div className="font-display text-lg font-bold">Guest list & RSVP</div><p className="text-xs text-mut">Every invitation carries an explicit guest allowance. No silent plus-ones.</p></div><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search guest, email or code" className="max-w-xs"/><Button onClick={()=>setGuestOpen(true)}>+ Add guest</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[12px]"><thead className="bg-ink/[.025] text-[10px] uppercase tracking-wider text-faint"><tr><th className="px-5 py-3">Guest</th><th>RSVP</th><th>Allowed</th><th>Confirmed</th><th>QR</th><th>Table</th><th>Arrival</th><th></th></tr></thead><tbody>{filtered.map(g=><tr key={g.id} className="border-t border-line hover:bg-white"><td className="px-5 py-3"><div className="font-semibold">{g.name}</div><div className="text-[10px] text-mut">{g.email} · {g.inviteCode}</div></td><td><Badge tone={statusTone[g.rsvp]}>{g.rsvp}</Badge></td><td>{g.allowedGuests}</td><td>{g.confirmedGuests}</td><td>{g.qrIssued?'Issued':'Not issued'}</td><td>{g.table||'—'}</td><td>{g.checkedIn}/{Math.min(g.allowedGuests,g.confirmedGuests)}</td><td><select value={g.rsvp} onChange={e=>{updateGuest(event.id,g.id,{rsvp:e.target.value as RSVPStatus,confirmedGuests:e.target.value==='confirmed'?Math.max(1,g.confirmedGuests):g.confirmedGuests});refresh()}} className="rounded border border-line2 bg-white px-2 py-1 text-[11px]"><option value="pending">pending</option><option value="invited">invited</option><option value="confirmed">confirmed</option><option value="declined">declined</option><option value="waitlist">waitlist</option></select></td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="px-5 py-12 text-center text-mut">No guests yet. Add the first guest or import your existing attendee list.</td></tr>}</tbody></table></div></Card>}

    {tab==='expenses'&&<Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-line p-5"><div><div className="font-display text-lg font-bold">Event expenses</div><p className="text-xs text-mut">Track the actual cost of the event against revenue and confirmed headcount.</p></div><Button onClick={()=>setExpenseOpen(true)}>+ Add expense</Button></div><div className="grid gap-3 p-5 sm:grid-cols-3"><div className="rounded-xl border border-line p-4"><div className="text-[10px] uppercase tracking-wider text-faint">Total cost</div><div className="mt-1 text-2xl font-black">{db.settings.currency} {totalExpenses.toLocaleString()}</div></div><div className="rounded-xl border border-line p-4"><div className="text-[10px] uppercase tracking-wider text-faint">Cost / confirmed guest</div><div className="mt-1 text-2xl font-black">{db.settings.currency} {confirmed?Math.round(totalExpenses/confirmed).toLocaleString():'0'}</div></div><div className="rounded-xl border border-line p-4"><div className="text-[10px] uppercase tracking-wider text-faint">Net after expenses</div><div className="mt-1 text-2xl font-black">{db.settings.currency} {balance.toLocaleString(undefined,{maximumFractionDigits:0})}</div></div></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-[12px]"><thead className="bg-ink/[.025] text-[10px] uppercase tracking-wider text-faint"><tr><th className="px-5 py-3">Category</th><th>Description</th><th>Amount</th><th>Paid</th><th></th></tr></thead><tbody>{active.expenses.map(e=><tr key={e.id} className="border-t border-line"><td className="px-5 py-3"><Badge>{e.category}</Badge></td><td>{e.description}</td><td className="font-semibold">{db.settings.currency} {e.amount.toLocaleString()}</td><td>{e.paid?'Yes':'Outstanding'}</td><td><button onClick={()=>{deleteExpense(event.id,e.id);refresh()}} className="text-[11px] font-semibold text-bad">Delete</button></td></tr>)}{!active.expenses.length&&<tr><td colSpan={5} className="px-5 py-12 text-center text-mut">No expenses recorded.</td></tr>}</tbody></table></div></Card>}

    {tab==='seating'&&<Card className="p-5"><div className="flex items-center justify-between"><div><div className="font-display text-lg font-bold">Seating & floor plan</div><p className="text-xs text-mut">Signature events can allocate confirmed guests before the day.</p></div><Button onClick={()=>setTableOpen(true)}>+ Add table</Button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{active.tables.map(t=><div key={t.id} className="rounded-2xl border border-line bg-white p-5"><div className="flex items-center justify-between"><div className="font-display text-xl font-bold">{t.name}</div><Badge>{t.assigned}/{t.capacity}</Badge></div><div className="mt-5 h-2 rounded-full bg-ink/[.08]"><div className="h-full rounded-full bg-teal" style={{width:`${Math.min(100,t.assigned/t.capacity*100)}%`}}/></div><p className="mt-3 text-xs text-mut">Available seats: {Math.max(0,t.capacity-t.assigned)}</p></div>)}</div></Card>}

    {tab==='access'&&<AccessPanel eventId={event.id} ops={active} onRefresh={refresh} toast={toast}/>} 

    <Modal open={guestOpen} onClose={()=>setGuestOpen(false)} title="Add guest" wide><div className="grid gap-4 sm:grid-cols-2"><Field label="Guest name"><Input value={guest.name} onChange={e=>setGuest({...guest,name:e.target.value})}/></Field><Field label="Email"><Input type="email" value={guest.email} onChange={e=>setGuest({...guest,email:e.target.value})}/></Field><Field label="Phone / WhatsApp"><Input value={guest.phone} onChange={e=>setGuest({...guest,phone:e.target.value})}/></Field><Field label="Allowed guests"><Input type="number" min={1} value={guest.allowedGuests} onChange={e=>setGuest({...guest,allowedGuests:Number(e.target.value)})}/></Field><Field label="Confirmed guests"><Input type="number" min={0} max={guest.allowedGuests} value={guest.confirmedGuests} onChange={e=>setGuest({...guest,confirmedGuests:Number(e.target.value)})}/></Field><Field label="RSVP"><Select value={guest.rsvp} onChange={e=>setGuest({...guest,rsvp:e.target.value as RSVPStatus})}><option value="invited">Invited</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="declined">Declined</option><option value="waitlist">Waitlist</option></Select></Field><Field label="Table"><Input value={guest.table} onChange={e=>setGuest({...guest,table:e.target.value})}/></Field><Field label="Internal notes"><Textarea value={guest.notes} onChange={e=>setGuest({...guest,notes:e.target.value})}/></Field></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={()=>setGuestOpen(false)}>Cancel</Button><Button onClick={addGuestNow}>Create invitation</Button></div></Modal>
    <Modal open={expenseOpen} onClose={()=>setExpenseOpen(false)} title="Log event expense"><div className="space-y-4"><Field label="Category"><Select value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}><option>Venue</option><option>Catering</option><option>Production</option><option>Security</option><option>Transport</option><option>Staff</option><option>Marketing</option><option>Other</option></Select></Field><Field label="Description"><Input value={expense.description} onChange={e=>setExpense({...expense,description:e.target.value})}/></Field><Field label={`Amount (${db.settings.currency})`}><Input type="number" min={0} value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={expense.paid} onChange={e=>setExpense({...expense,paid:e.target.checked})}/> Paid</label><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setExpenseOpen(false)}>Cancel</Button><Button onClick={addExpenseNow}>Save expense</Button></div></div></Modal>
    <Modal open={tableOpen} onClose={()=>setTableOpen(false)} title="Add table"><div className="space-y-4"><Field label="Table name"><Input value={table.name} onChange={e=>setTable({...table,name:e.target.value})}/></Field><Field label="Capacity"><Input type="number" min={1} value={table.capacity} onChange={e=>setTable({...table,capacity:e.target.value})}/></Field><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setTableOpen(false)}>Cancel</Button><Button onClick={addTableNow}>Add table</Button></div></div></Modal>
  </div>;
}

function AccessPanel({ eventId, ops, onRefresh, toast }: { eventId:string; ops: ReturnType<typeof getOps>; onRefresh:()=>void; toast:(t:any)=>void }) {
  const [code,setCode]=useState("");
  const [result,setResult]=useState<{ok:boolean;reason?:string;name?:string}|null>(null);
  const find=ops.guests.find(g=>g.inviteCode.toLowerCase()===code.trim().toLowerCase());
  const admit=()=>{ if(!find) return setResult({ok:false,reason:"No guest matches that access code."}); const r=checkInGuest(eventId,find.id,1); setResult({ok:r.ok,reason:r.reason,name:find.name}); onRefresh(); if(r.ok) toast({kind:"ok",title:"Access granted",desc:`${find.name} admitted.`}); else toast({kind:"bad",title:"Access denied",desc:r.reason}); };
  return <Card className="p-6"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><div className="code-pill text-[9px] uppercase tracking-[.2em] text-faint">Gate control</div><h2 className="mt-2 font-display text-3xl font-black">One code.<br/>One controlled entry.</h2><p className="mt-4 text-sm leading-6 text-mut">The system checks RSVP state, issued access, allowed guest count and prior admissions before granting entry.</p><div className="mt-6 flex gap-2"><Input value={code} onChange={e=>{setCode(e.target.value);setResult(null)}} placeholder="ENT-XXXXXX" onKeyDown={e=>e.key==='Enter'&&admit()}/><Button onClick={admit}>Admit</Button></div>{result&&<div className={`mt-4 rounded-xl border p-4 text-sm ${result.ok?'border-ok/30 bg-okdim text-ok':'border-bad/30 bg-baddim text-bad'}`}><div className="font-bold">{result.ok?'ACCESS GRANTED':'ACCESS DENIED'}</div><div className="mt-1 text-xs opacity-80">{result.name||result.reason}</div></div>}</div><div><div className="mb-3 text-[10px] uppercase tracking-wider text-faint">Recent gate-ready guests</div><div className="space-y-2">{ops.guests.filter(g=>g.qrIssued).slice(0,8).map(g=><button key={g.id} onClick={()=>setCode(g.inviteCode)} className="flex w-full items-center justify-between rounded-xl border border-line bg-white p-3 text-left hover:border-faint"><span><span className="block text-sm font-semibold">{g.name}</span><span className="text-[10px] text-mut">{g.inviteCode} · {g.checkedIn}/{Math.min(g.allowedGuests,g.confirmedGuests)} admitted</span></span><Badge tone={g.checkedIn?'ok':'teal'}>{g.checkedIn?'Checked in':'Ready'}</Badge></button>)}{!ops.guests.length&&<div className="rounded-xl border border-dashed border-line2 p-8 text-center text-sm text-mut">Add guests to activate access control.</div>}</div></div></div></Card>;
}
