import { useEffect, useState } from "react";
import { IArrowR, ICheck, IScan, ITicket, IUsers } from "./icons";

const plans = [
  { name: "Guest Access", price: "₦90,000", note: "Invite-only, RSVP, free events, private dinners, weddings", guests: "Up to 150 guests", features: ["Branded event microsite", "RSVP & guest list management", "QR access passes", "Email + WhatsApp delivery", "Check-in portal", "Basic seating lookup"] },
  { name: "Premium Ticketing", price: "₦170,000", note: "Paid events, conferences, masterclasses, networking events", guests: "Up to 300 guests", popular: true, features: ["Everything in Guest Access", "Paid ticket types", "Paystack checkout", "QR ticket generation", "Admin dashboard", "Payment & check-in analytics"] },
  { name: "Signature", price: "₦410,000", note: "Corporate events, galas, awards, lifestyle experiences", guests: "Up to 750 guests", features: ["Everything in Premium Ticketing", "Custom branding & subdomain", "Seating & table management", "Speaker, agenda & sponsor sections", "Multiple check-in staff", "Advanced exports & priority support"] },
];

const film = [
  "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1200&q=80",
];

export default function EntriaShowcase({ onCreateEvent }: { onCreateEvent?: () => void }) {
  const [active, setActive] = useState(0);
  useEffect(() => { const t = window.setInterval(() => setActive(v => (v + 1) % film.length), 3500); return () => clearInterval(t); }, []);
  return <div className="entria-site">
    <header className="es-nav"><button className="es-brand" onClick={() => window.scrollTo({top:0,behavior:"smooth"})}><b>E</b><span>ENTRIA<small>EVENT TECHNOLOGIES</small></span></button><nav><a href="#events">Events</a><a href="#experience">Experience</a><a href="#pricing">Pricing</a><a href="#how">How it works</a></nav><button onClick={onCreateEvent} className="es-staff">Staff portal ↗</button></header>

    <section className="es-hero">
      <div className="es-video-bg"><div className="es-video-shade"/>{film.map((src,i)=><img key={src} src={src} alt="" className={i===active?"active":""}/>)}</div>
      <div className="es-hero-grid"/>
      <div className="es-hero-content"><div className="es-kicker"><i/> NIGERIA · EVENT ACCESS · GUEST EXPERIENCE</div><h1>YOUR EVENT.<br/><em>YOUR PEOPLE.</em><br/>YOUR ROOM.</h1><p>From the first invitation to the final scan, Entria gives organisers control of the guest experience — beautifully.</p><div className="es-hero-actions"><button onClick={() => document.getElementById("events")?.scrollIntoView({behavior:"smooth"})} className="es-gold">Explore the experience <IArrowR size={16}/></button><button onClick={onCreateEvent} className="es-outline">Organise an event</button></div><div className="es-location"><span>BUILT FOR HOW NIGERIAN EVENTS ACTUALLY RUN</span><b>WhatsApp · RSVP · QR · CHECK-IN</b></div></div>
      <div className="es-film-controls">{film.map((_,i)=><button key={i} onClick={()=>setActive(i)} className={i===active?"on":""}/>)}</div>
    </section>

    <section id="events" className="es-section es-light"><div className="es-section-head"><div><span className="es-label">01 / WHAT'S ON</span><h2>Events that feel<br/><em>worth attending.</em></h2></div><p>Whether it is a private dinner, a celebrity celebration, a conference, masterclass, wedding or festival, every event gets its own branded digital experience.</p></div><div className="es-event-feature"><div className="es-event-image"><img src={film[1]} alt="Event atmosphere"/><div className="es-event-overlay"><span>FEATURED EXPERIENCE</span><strong>PRIVATE NIGHT<br/>LAGOS</strong><small>Victoria Island · Lagos, Nigeria</small></div></div><div className="es-event-info"><span className="es-label">THE GUEST JOURNEY</span><h3>Know where you're going.<br/>Know what you're getting.</h3><div className="es-event-meta"><div><small>DATE</small><b>Set by organiser</b></div><div><small>VENUE</small><b>Released by organiser</b></div><div><small>ACCESS</small><b>Invitation / Ticket</b></div></div><p>Public event pages can show the exact event date, venue, ticket tiers, availability and what is included. Private events can keep venue details hidden until the guest is confirmed.</p><button onClick={onCreateEvent} className="es-darkbtn">Create an event page <IArrowR size={15}/></button></div></div></section>

    <section id="experience" className="es-section es-black"><div className="es-section-head"><div><span className="es-label">02 / THE EXPERIENCE</span><h2>More than a<br/><em>ticket.</em></h2></div><p>Entria's own site describes three ways to work with the platform: full-service concierge, self-serve Arrivals, and WhatsApp-first Pulse. This experience brings those ideas into one modern product.</p></div><div className="es-cards"><article><div className="es-icon"><IUsers/></div><span>01</span><h3>INVITATIONS</h3><p>Branded, mobile-first invites through WhatsApp and email. Personalise the guest name, table and event details.</p></article><article><div className="es-icon"><ITicket/></div><span>02</span><h3>RSVP + TICKETS</h3><p>RSVP, free admission or paid ticketing. Early bird, regular, VIP, promo codes, add-ons and payment confirmation.</p></article><article><div className="es-icon"><IScan/></div><span>03</span><h3>QR CHECK-IN</h3><p>Every guest receives a unique access credential. Scan once at the gate and prevent reuse or uninvited extras.</p></article><article><div className="es-icon">✦</div><span>04</span><h3>SEATING + CONTROL</h3><p>Visual floor plans, table assignments, live arrivals and event numbers for the team running the room.</p></article></div></section>

    <section id="pricing" className="es-section es-gold-section"><div className="es-section-head"><div><span className="es-label dark">03 / PRICING</span><h2>Pick your<br/><em>gate.</em></h2></div><p>Current public pricing from Entria4Events: per-event plans for guest access, premium ticketing and signature experiences, plus monthly plans for repeat organisers.</p></div><div className="es-pricing">{plans.map(plan=><article key={plan.name} className={plan.popular?"popular":""}>{plan.popular&&<div className="es-popular">MOST POPULAR</div>}<span className="es-plan-name">{plan.name}</span><h3>{plan.price}<small>/ event</small></h3><p>{plan.note}</p><strong className="es-guests">{plan.guests}</strong><ul>{plan.features.map(f=><li key={f}><ICheck size={14}/>{f}</li>)}</ul><button onClick={onCreateEvent}>{plan.name === "Premium Ticketing" ? "Launch ticketing" : `Start with ${plan.name}`} <IArrowR size={14}/></button></article>)}</div><div className="es-monthly"><span>REPEAT ORGANISERS</span><b>Studio ₦100k/mo · Business ₦250k/mo · Agency ₦500k/mo</b><small>3% · 2.5% · 2% per paid ticket respectively</small></div></section>

    <section id="how" className="es-section es-light"><div className="es-center"><span className="es-label">04 / HOW IT WORKS</span><h2>From invite<br/><em>to entrance.</em></h2><p>The flow is deliberately simple for guests and powerful for the team behind the event.</p></div><div className="es-timeline"><div><b>01</b><h3>INVITE</h3><p>Send a branded event link, email or WhatsApp invitation.</p></div><div><b>02</b><h3>CONFIRM</h3><p>Guest RSVPs or selects a ticket and pays online.</p></div><div><b>03</b><h3>RECEIVE</h3><p>Personal QR access pass arrives digitally.</p></div><div><b>04</b><h3>ENTER</h3><p>Gatekeeper scans. Valid pass admits. Used pass rejects.</p></div></div></section>

    <footer className="es-footer"><div><b>ENTRIA</b><span>Guest experience, built for how Nigerian events actually run.</span></div><div><span>Lagos, Nigeria</span><span>hello@entria4events.com</span><span>© 2026 Entria Event Technologies Limited</span></div></footer>
  </div>;
}
